### ISSUE TITLE
Automatic Fix all damaged genes

### ISSUE THREAD

**Issue by zachadel** [zachadel/GenomeEvolution#112]
Add a button to use the "fix damaged genes" tool on all damaged genes

**Comment by RyanMalt** [comment]
Should be broken up into a primary function and a helper function: auto_fix_one, then auto_fix_all.

-func auto_fix_one(chromosome) -> bool
    *takes in a single chromosome and repairs a single gene, scanning from left to right (0 to final index)
    *if no fixing is necessary, return false
-func auto_fix_all(chrom_pair) -> int
    *This function should fix all damaged genes beginning from the topmost chromosome and scanning from left to right.
    *Should rely on auto_fix_one to get the job done
    *Takes in a chrom_pair as its only argument (no need for a preference list or priority list here since fixing damaged genes is a binary operation: either you fix it or you don't, there is no choice involved)
