### ISSUE TITLE
Replication Animation

### ISSUE THREAD

**Issue by zachadel** [zachadel/GenomeEvolution#170]
- [x] When mitosis or meiosis is selected, an animation screen appears similar to the tutorial screen showing the copying of each gene tile. 
- [x] Genes get better or worse using the same coloring pattern as is already present on the choice screen, using values that are already calculated by the game
- [x] Genes that die (become pseudogenes should be obvious. 
- [x] Genes that gain a new skill should be obvious
- [x] when there are more genes than space, side scrolling should make it obvious that the chromosome continues
- [x] Players should be able to skip this animation by clicking "skip" or "next"

**Comment by LanceAbuan** [comment]
This has been finished for a while. Closing.
