### ISSUE TITLE
infinitely increasing resources

### ISSUE THREAD

**Issue by zachadel** [zachadel/GenomeEvolution#196]
just figured out why i am having so much trouble optimizing resource values. 

here is game 1: 
![image](https://user-images.githubusercontent.com/70545319/158212060-60b8ef68-65ad-4e83-8778-ddf6ae1bdede.png)

game 2: 
![image](https://user-images.githubusercontent.com/70545319/158211296-7ab69393-b7eb-470b-aa41-a77b66e8b589.png)

game 3: 
![image](https://user-images.githubusercontent.com/70545319/158211358-bc2ded7b-29b5-4f87-b094-0fe231e452f8.png)

game 4: 
![image](https://user-images.githubusercontent.com/70545319/158212275-4e3c3c6c-252c-415c-ab87-c5c8e7aa86f0.png)

game 5: 
![image](https://user-images.githubusercontent.com/70545319/158211478-15632a0a-49af-4a7a-bb5a-9b9642d79968.png)

game 6: 
![image](https://user-images.githubusercontent.com/70545319/158211552-48944e95-9f42-4ab8-bf9c-d10f0d552088.png)

this also appears to be happening with simple (sugars, amino acids, simple fats) but not complex resources (bread, steak, fats). Also, thankfully not Mercury (Hg). A re-fresh of the browser reverts back to normal, but this also overrides the "save settings" function.

**Comment by LanceAbuan** [comment]
Issue found and solved.
