### ISSUE TITLE
Damaged genes are replicated exactly

### ISSUE THREAD

**Issue by ajidevelop** [zachadel/GenomeEvolution#66]
At present, if damaged genes are present during replication or copy repair, the tile is copied exactly, meaning a new damaged gene tile is created. However, there is a missing piece. Following this step, each damaged gene should be repaired automatically (and independently) using the “fix damaged genes” mechanic, except with a penalty that shifts outcomes in favor of major downgrade/pseudogene. Thus, the player is incentivized to repair them manually prior to replication (or not, in the case of transposons/blanks where downgrades are beneficial).

**Comment by RyanMalt** [comment]
We will need a repair all button for damaged genes.  Then put a block on replication until all genes are repaired.
