### ISSUE TITLE
Update amino acid conversion process

### ISSUE THREAD

**Issue by ajidevelop** [zachadel/GenomeEvolution#73]
Converting amino acids to sugars should also add N to your elements box. Doing the reverse would cost N.

**Comment by samuelj1323** [comment]
- [ ] When you convert from amino acid to sugar you need to add to nitrogen storage, 
- [ ] When you convert from sugar to amino acids you need to subtract from nitrogen. 
- [ ] Have warnings when you can't go over your storage level or under.,
